name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'   # Triggers when a tag is pushed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: vars
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/offendo/blv:${TAG} \
            -t ghcr.io/offendo/blv:latest \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/offendo/blv:${TAG}
          docker push ghcr.io/offendo/blv:latest
